## Preambule
site_name: site_mkdocs
site_description: "un site sur quelque chose"
site_author: Nathalie_Olcese

theme:
   name: readthedocs # mkdocs

## Architecture
nav:
   - Accueil: index.md
   - pense-bete: pense_bete.md

## Extensions